### ISSUE TITLE
How to stop the application ?

### ISSUE THREAD

**Issue by NilsMinor** [adafruit/Pi_Eyes#13]
Hi, 

I followed the instructions on Adafruit to install Pi_Eyes using your script. It worked like charm but how is it possible to avoid an automatic start? Or how can I stop the application ? I've tested all key codes and tried to start a new terminal but I think the while-true of the application prevents the linux from recognizing my commands ^^ any idea ?

However, your software is awesome thanks for sharing :)
- Nils

**Comment by RoisinHoward** [comment]
If you have a look in the script /etc/rc.local you will see there are lines to start the script automatically on boot:
 /usr/local/bin/gpio-halt 4 &
 /home/pi/Pi_Eyes/fbx2 -i -b 12000000 &
 cd /home/pi/Pi_Eyes && python eyes.py --radius 240 &

Just remove these lines if you do not want the script run on start up.

**Comment by NilsMinor** [comment]
Thanks :)
