### ISSUE TITLE
How do you rotate the screen? 🤔

### ISSUE THREAD

**Issue by sorryaboutyourcats** [adafruit/Pi_Eyes#15]
I attempted to rotate both screens by adding this to eyes.py, but it didn't work:
```
DISPLAY.set_rotate(90)
```

I also noticed that there is a rotate option [here](https://github.com/adafruit/Adafruit_CircuitPython_RGB_Display), but it uses a different way to create the display.
```
display = ST7789(
    spi,
    rotation=90,
    etc...
```

That being said, does anyone know a way to rotate the displays?

Thanks in advance! 😸👍

**Comment by ladyada** [comment]
this is a completly hard-coded display system.
you cant without changing the init code
we don't have a tutorial, guide or info on how to do it - so rotation is unsupported
