### ISSUE TITLE
Not working on a frsh install on RAspberry PI 3B+

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [adafruit/Pi_Eyes#19]
Hi,

I have just installed a lite version of PI OS, update and upgrade it.
Then i use the process described here : https://learn.adafruit.com/animated-snake-eyes-bonnet-for-raspberry-pi/software-installation
I use two TFT ISP 240x240 pixels.
(On a previous install a few month ago it was working perfectly).

I have these msg of errors:

Can't open primary display
and:

```
rc.local: Traceback
File "/boot/Pi_eyes/eyes.py line 9 in module 
import pi3d
…
File "/usr/local/lib/python3.9/dist-packages/pi3d/constatnts/gl.py", line 387, in set_gles_function_args
gles.glActiveTexture.argtypes = [GLenum] #
AttributeError: 'NoneType' object has no attribute 'glActiveTexture'
```

**Comment by Jacques-Olivier-Farcy** [comment]
Maybe it is linked to this issue:
https://github.com/tipam/pi3d/issues/259

**Comment by paddywwoof** [comment]
Hi, can you confirm that the OS version is buster not bullseye. Or, if it is bullseye that it's not tied up with the revised GL driver?

There's some discussion and, I think, working solution to that problem here.
https://github.com/helgeerbe/picframe/issues/195#issuecomment-982999227

Let me know what you find.

Paddy

**Comment by Jacques-Olivier-Farcy** [comment]
Hi @paddywwoof ,

Yesterday i tried with this version of PI OS [raspios armhf buster lite](http://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip.torrent)

And after a long update / upragde i installed snake eyes and it is working fine

**Comment by Jacques-Olivier-Farcy** [comment]
Yes

**Comment by rayqunn** [comment]
I ended up here as I didn't read the adafruit instructions properly and installed latest raspberry pi os lite instead of legacy one. Lesson learned RTFM.
