### ISSUE TITLE
Could you put the LICENCE file and ...

### ISSUE THREAD

**Issue by dglaude** [adafruit/Pi_Eyes#2]
Could you place the typical Adafruit MIT licence (fbx2.c say it is MIT). (I need this for my fork)

Also, could you make this git repository more likely to be found or understood for someone not coming from the Eyes bonnet learn page.
Such as filling this: No description, website, or topics provided.
And of course a readme.md, even it is just a link.

Regards

**Comment by ladyada** [comment]
hiya please submit a PR with the changes you'd like and we'll take a look!
