### ISSUE TITLE
Pi_Eyes mouse/joystick control

### ISSUE THREAD

**Issue by nineseventytwo** [adafruit/Pi_Eyes#7]
I've tried to revise the code to include either joystick or mouse control of the eye movement. Could this be added as an option to the code so anyone with a pi and an hdmi output can control the eyes.
[mouse_eye_2 2.txt](https://github.com/adafruit/Pi_Eyes/files/2489720/mouse_eye_2.2.txt)

**Comment by ladyada** [comment]
wanna add this example as a pull request?
