### ISSUE TITLE
SPI1_SCLK not working，I can not drive two TFT eyes . help!!!

### ISSUE THREAD

**Issue by Afantor** [adafruit/Pi_Eyes#8]
I use Raspberry Pi 3B+, software is latest。
I run the cmd  : 
pi@raspberry:~ $ sudo bash pi-eyes.sh 
is success and one TFT show the eyes image，but another not work.
I check P21(BCM) the pin is no anything signal。
help to me ,Thank you

**Comment by ladyada** [comment]
hiya, tech support is handled in the adafruit forums, not in github issues
